server:
  port: 18888
  servlet:
    contextPath: /mailXpert
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb://${db-username}:${db-password}@localhost:27017
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            redirect-uri: https://gurula.cc/mailXpert/login/oauth2/code/google
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/gmail.readonly
              - https://www.googleapis.com/auth/gmail.compose
              - https://www.googleapis.com/auth/gmail.send
config:
  globalDomain: https://gurula.cc/mailXpert/
  geminiApiKey: ${gemini-api-key}
  apiKey: ${openai-api-key}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG